service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-chatbot
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.uploadBucket}/*
custom:
  uploadBucket: ${self:service}-${self:provider.stage}-bjm
functions:
  hello:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: post
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      BOT_ACCESS_TOKEN: <TOKEN>
      VERIFICATION_TOKEN: <TOKEN>
      UPLOAD_BUCKET: ${self:custom.uploadBucket}
      SLACK_HOSTNAME: 'files.slack.com'
      TEMP_FOLDER: '/tmp/'
  faceswap:
    handler: faceswap.execute
    events:
      - s3:
          bucket: ${self:custom.uploadBucket}
          event: s3:ObjectCreated:*
